export const VARIATION_CAUSE_OPTIONS = [
  'As per Client Request',
  'As per Client Instruction',
  'As per Client Selection',
  'As per Client Design Change',
  'As per Revised Client Requirement',
  'As per Interior Design Drawings',
  'As per Revised Interior Design Drawings',
  'As per Architectural Design Changes',
  'As per Revised Drawings',
  'As per Additional Scope Requested by Client',
  'As per Consultant Instruction',
  'As per Consultant Requirement',
  'As per Consultant Comments',
  'As per Consultant Approval Requirement',
  "As per Consultant's Technical Recommendation",
  'As per Site Instruction',
  'As per Site Requirement',
  'As per Actual Site Conditions',
  'As per Unforeseen Site Conditions',
  'As per Existing Site Conditions',
  'As per Site Coordination Requirement',
  'As per Technical Requirement',
  'As per Construction Requirement',
  'As per MEP Coordination Requirement',
  'As per Structural Requirement',
  'As per Authority Requirement',
  'As per Municipality Requirement',
  'As per Civil Defence Requirement',
  'As per Latest Authority Regulations',
  'As per Safety Requirement',
  'As per Accessibility Requirement',
  'As per Approved Material Selection',
  'As per Market Price Increment',
  'Due to Material Price Increase',
  'Due to Change of Material Specification',
  'Due to Material Upgrade',
  'Due to Change of Approved Material',
  'Due to Material Unavailability',
  'Due to Discontinuation of Specified Material',
  'Due to Change of Supplier',
  'Due to Additional Quantity',
  'Due to Actual Quantity Executed',
  'Due to Increase in Scope of Work',
  'Due to Change in Scope of Work',
  'Due to Additional Works Required at Site',
  'Due to Modification of Existing Works',
  'Due to Omission and Replacement of Works',
  'Due to Design Coordination',
  'Due to MEP Coordination',
  'Due to Clash Resolution',
  'Due to Revised Construction Method',
  'Due to Additional Protection Works',
  'Due to Compliance Requirements',
  'Due to Change in Statutory Requirements',
  'Due to Discrepancy Between Drawings and Actual Site Conditions',
];

// Arabic display labels, keyed by the canonical English option (the stored
// value). Kept as a translation map — not a parallel array — so the two stay
// in sync even if VARIATION_CAUSE_OPTIONS is reordered later.
export const VARIATION_CAUSE_OPTIONS_AR = {
  'As per Client Request': 'حسب طلب العميل',
  'As per Client Instruction': 'حسب تعليمات العميل',
  'As per Client Selection': 'حسب اختيار العميل',
  'As per Client Design Change': 'حسب تغيير التصميم من العميل',
  'As per Revised Client Requirement': 'حسب متطلبات العميل المعدّلة',
  'As per Interior Design Drawings': 'حسب مخططات التصميم الداخلي',
  'As per Revised Interior Design Drawings': 'حسب مخططات التصميم الداخلي المعدّلة',
  'As per Architectural Design Changes': 'حسب تغييرات التصميم المعماري',
  'As per Revised Drawings': 'حسب المخططات المعدّلة',
  'As per Additional Scope Requested by Client': 'حسب نطاق عمل إضافي طلبه العميل',
  'As per Consultant Instruction': 'حسب تعليمات الاستشاري',
  'As per Consultant Requirement': 'حسب متطلبات الاستشاري',
  'As per Consultant Comments': 'حسب ملاحظات الاستشاري',
  'As per Consultant Approval Requirement': 'حسب متطلبات اعتماد الاستشاري',
  "As per Consultant's Technical Recommendation": 'حسب التوصية الفنية للاستشاري',
  'As per Site Instruction': 'حسب تعليمات الموقع',
  'As per Site Requirement': 'حسب متطلبات الموقع',
  'As per Actual Site Conditions': 'حسب ظروف الموقع الفعلية',
  'As per Unforeseen Site Conditions': 'حسب ظروف موقع غير متوقعة',
  'As per Existing Site Conditions': 'حسب ظروف الموقع الحالية',
  'As per Site Coordination Requirement': 'حسب متطلبات التنسيق في الموقع',
  'As per Technical Requirement': 'حسب المتطلبات الفنية',
  'As per Construction Requirement': 'حسب متطلبات التنفيذ',
  'As per MEP Coordination Requirement': 'حسب متطلبات تنسيق الأعمال الكهروميكانيكية',
  'As per Structural Requirement': 'حسب المتطلبات الإنشائية',
  'As per Authority Requirement': 'حسب متطلبات الجهة المختصة',
  'As per Municipality Requirement': 'حسب متطلبات البلدية',
  'As per Civil Defence Requirement': 'حسب متطلبات الدفاع المدني',
  'As per Latest Authority Regulations': 'حسب أحدث لوائح الجهات المختصة',
  'As per Safety Requirement': 'حسب متطلبات السلامة',
  'As per Accessibility Requirement': 'حسب متطلبات إمكانية الوصول',
  'As per Approved Material Selection': 'حسب اختيار المواد المعتمدة',
  'As per Market Price Increment': 'حسب ارتفاع أسعار السوق',
  'Due to Material Price Increase': 'بسبب ارتفاع سعر المواد',
  'Due to Change of Material Specification': 'بسبب تغيير مواصفات المواد',
  'Due to Material Upgrade': 'بسبب ترقية المواد',
  'Due to Change of Approved Material': 'بسبب تغيير المادة المعتمدة',
  'Due to Material Unavailability': 'بسبب عدم توفر المواد',
  'Due to Discontinuation of Specified Material': 'بسبب توقف إنتاج المادة المحددة',
  'Due to Change of Supplier': 'بسبب تغيير المورد',
  'Due to Additional Quantity': 'بسبب كمية إضافية',
  'Due to Actual Quantity Executed': 'بسبب الكمية الفعلية المنفذة',
  'Due to Increase in Scope of Work': 'بسبب زيادة نطاق العمل',
  'Due to Change in Scope of Work': 'بسبب تغيير نطاق العمل',
  'Due to Additional Works Required at Site': 'بسبب أعمال إضافية مطلوبة في الموقع',
  'Due to Modification of Existing Works': 'بسبب تعديل الأعمال القائمة',
  'Due to Omission and Replacement of Works': 'بسبب حذف واستبدال أعمال',
  'Due to Design Coordination': 'بسبب تنسيق التصميم',
  'Due to MEP Coordination': 'بسبب تنسيق الأعمال الكهروميكانيكية',
  'Due to Clash Resolution': 'بسبب حل تعارضات التصميم',
  'Due to Revised Construction Method': 'بسبب تعديل طريقة التنفيذ',
  'Due to Additional Protection Works': 'بسبب أعمال حماية إضافية',
  'Due to Compliance Requirements': 'بسبب متطلبات الامتثال',
  'Due to Change in Statutory Requirements': 'بسبب تغيير المتطلبات القانونية',
  'Due to Discrepancy Between Drawings and Actual Site Conditions': 'بسبب تعارض بين المخططات وظروف الموقع الفعلية',
};
