import { useMemo, useState, useEffect, useRef } from "react";
import useViewMode from "../hooks/useViewMode";
import { useTranslation } from "react-i18next";

import { api } from "../../../../services/api";

// Design System Components
import {
  FormField,
  FormGrid,
  FormInput,
  FormViewField,
} from "../../../../components/ui/form";

// Components
import ErrorDialog from "../components/ErrorDialog";
import PersonField from "../components/PersonField";
import YesNoChips from "../../../../components/ui/YesNoChips";
import WizardShell from "../components/WizardShell";
import StepActions from "../components/StepActions";
import RtlSelect from "../../../../components/forms/RtlSelect";
import Button from "../../../../components/common/Button";
import FileAttachmentView from "../../../../components/file-upload/FileAttachmentView";
import FileUpload from "../../../../components/file-upload/FileUpload";
import DateInput from "../../../../components/forms/DateInput";

import useLicense from "../../../../hooks/useLicense";
import useStepSave from "../hooks/useStepSave";
import VerifiableField from "../components/VerifiableField";
import formatCNLicense from "../utils/formatCNLicense";
import { toIsoDate, formatProjectNumber, formatDate } from "../../../../utils/formatters";
import { formatLicenseServerErrors } from "../../../../utils/errors/licenseErrorFormatter";
import { getErrorMessage } from "../../../../utils/errorHandler";
import { extractFileNameFromUrl, fetchFileWithAuth } from "../../../../utils/helpers/file";
import { logger } from "../../../../utils/logger";
import { renameFileForUpload } from "../../../../utils/helpers/file";
import useTenantNavigate from '../../../../hooks/useTenantNavigate';

export default function LicenseStep({ projectId, onPrev, onNext, isView: isViewProp, isNewProject = false, onLicenseReady, isActive = true, onDocFilesChange, onFormSectionChange, hasBlockingErrors = false }) {
  const { t } = useTranslation();
  const navigate = useTenantNavigate();
  const { form, setForm, setF, owners, existingId, setExistingId, isView: isViewState, setIsView } = useLicense(projectId);

  const [viewMode, updateViewMode] = useViewMode(isViewProp, isViewState, setIsView);
  const { isSaving, errorMsg, setErrorMsg, runSave } = useStepSave();
  const navTimerRef = useRef(null);

  useEffect(() => {
    return () => clearTimeout(navTimerRef.current);
  }, []);
  const [buildingLicenseFileUrl, setBuildingLicenseFileUrl] = useState("");
  const [consultantStamp, setConsultantStamp] = useState(null);
  const [existingConsultantStampUrl, setExistingConsultantStampUrl] = useState(null);
  const [consultantStampCleared, setConsultantStampCleared] = useState(false);
  const [isLicenseNoAutoGenerated, setIsLicenseNoAutoGenerated] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [showLicensePanel, setShowLicensePanel] = useState(false);
  const [licenseZoom, setLicenseZoom] = useState(100);
  const [licensePreviewSrc, setLicensePreviewSrc] = useState("");
  const [previewError, setPreviewError] = useState("");
  const [verifiedFields, setVerifiedFields] = useState({});
  const [aiFilledFields, setAiFilledFields] = useState([]);
  const toggleVerify = (fieldName) => {
    setVerifiedFields(prev => ({ ...prev, [fieldName]: !prev[fieldName] }));

    if (buildingLicenseFileUrl || form.building_license_file instanceof File) {
      setShowLicensePanel(true);
      setLicenseZoom(175);
    }
  };

  useEffect(() => {
    if (!showLicensePanel) {
      setLicensePreviewSrc("");
      return;
    }

    let cancelled = false;
    let objectUrl = "";

    async function loadPreview() {
      setPreviewError("");

      try {
        if (form.building_license_file instanceof File) {
          objectUrl = URL.createObjectURL(form.building_license_file);
          if (!cancelled) setLicensePreviewSrc(objectUrl);
          return;
        }

        if (buildingLicenseFileUrl) {
          const blob = await fetchFileWithAuth(buildingLicenseFileUrl);
          objectUrl = URL.createObjectURL(blob);
          if (!cancelled) setLicensePreviewSrc(objectUrl);
        }
      } catch (error) {
        logger.error("Error loading license preview", error);
        if (!cancelled) {
          setLicensePreviewSrc("");
          setPreviewError(t("file_preview_failed") || "Could not preview file");
        }
      }
    }

    loadPreview();

    return () => {
      cancelled = true;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [showLicensePanel, form.building_license_file, buildingLicenseFileUrl, t]);

  // Sync body class so wizard-content shrinks when panel is open
  useEffect(() => {
    document.body.classList.toggle("pdf-panel-open", showLicensePanel);
    return () => document.body.classList.remove("pdf-panel-open");
  }, [showLicensePanel]);

  // Close preview panel when the user navigates away from this step
  useEffect(() => {
    if (!isActive) setShowLicensePanel(false);
  }, [isActive]);

  // Report the complete license section only when at least one field has meaningful data
  useEffect(() => {
    if (!form.license_no && !form.issue_date && !form.expiry_date) return;
    onFormSectionChange?.("license_section", {
      license_no:          form.license_no          || "",
      license_project_no:  form.license_project_no  || "",
      issue_date:          form.issue_date          || "",
      expiry_date:         form.expiry_date         || "",
      license_type:        form.license_type        || "",
    });
  }, [form.license_no, form.license_project_no, form.issue_date, form.expiry_date, form.license_type, onFormSectionChange]);

  const handleLicenseFileChange = async (file) => {
    setF("building_license_file", file);
    if (file instanceof File) {
      // Clear stale permit fields so old values don't cause false mismatches
      // while the new permit is being extracted.
      onFormSectionChange?.("license_section", null);
      onDocFilesChange?.("build_permit", file);
      setShowLicensePanel(true);
    }
    if (!file || !(file instanceof File)) return;

    setIsExtracting(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const { data: result } = await api.post("extract-license-data/", fd);

      if (result?.error === "wrong_document_type") {
        setF("building_license_file", null);
        setErrorMsg(t("wrong_document_type_building_permit"));
        return;
      }

      if (result?.data && Object.keys(result.data).length > 0) {
        const d = result.data;
        // Batch all extracted fields in one atomic state update — avoids race conditions
        setForm((prev) => {
          const next = { ...prev };
          if (d.license_type)                      next.license_type = d.license_type;
          if (d.license_project_no)                next.license_project_no = d.license_project_no;
          if (d.license_no)                        next.license_no = d.license_no;
          if (d.issue_date)                        next.issue_date = d.issue_date;
          if (d.design_consultant_name)            next.design_consultant_name = d.design_consultant_name;
          if (d.design_consultant_name_en)         next.design_consultant_name_en = d.design_consultant_name_en;
          if (d.design_consultant_license_no)      next.design_consultant_license_no = d.design_consultant_license_no;
          if (d.design_consultant_registration_no) next.design_consultant_registration_no = d.design_consultant_registration_no;
          // If consultant_same, mirror to supervision as well
          if (prev.consultant_same) {
            if (d.design_consultant_name)            next.supervision_consultant_name = d.design_consultant_name;
            if (d.design_consultant_name_en)         next.supervision_consultant_name_en = d.design_consultant_name_en;
            if (d.design_consultant_license_no)      next.supervision_consultant_license_no = d.design_consultant_license_no;
            if (d.design_consultant_registration_no) next.supervision_consultant_registration_no = d.design_consultant_registration_no;
          }
          return next;
        });
      }
      // Track which fields were populated by AI so user must verify them
      if (result?.data && Object.keys(result.data).length > 0) {
        const d = result.data;
        const newAiFields = [];
        if (d.license_type)                      newAiFields.push("license_type");
        if (d.license_project_no)                newAiFields.push("license_project_no");
        if (d.license_no)                        newAiFields.push("license_no");
        if (d.issue_date)                        newAiFields.push("issue_date");
        if (d.design_consultant_name)            newAiFields.push("design_name");
        if (d.design_consultant_name_en)         newAiFields.push("design_name_en");
        if (d.design_consultant_license_no)      newAiFields.push("design_license");
        if (d.design_consultant_registration_no) newAiFields.push("design_registration");
        if (newAiFields.length > 0) {
          setAiFilledFields((prev) => [...new Set([...prev, ...newAiFields])]);
        }
      }
    } catch (err) {
      if (err?.response?.data?.error === "wrong_document_type") {
        setF("building_license_file", null);
        setErrorMsg(t("wrong_document_type_building_permit"));
      } else {
        logger.warn("Could not extract data from license file", err);
      }
    } finally {
      setIsExtracting(false);
    }
  };

  const licProjectNoLabel = t("license_project_no");

  // Load saved file URL
  useEffect(() => {
    if (!projectId || !existingId) return;
    (async () => {
      try {
        const { data } = await api.get(`projects/${projectId}/license/`);
        if (Array.isArray(data) && data.length > 0) {
          const licenseData = data[0];
          if (licenseData.building_license_file) {
            setBuildingLicenseFileUrl(licenseData.building_license_file);
          }
          if (licenseData.consultant_stamp) {
            setExistingConsultantStampUrl(licenseData.consultant_stamp);
          }

          if (licenseData.license_project_no && licenseData.license_no) {
            const expectedLicenseNo = licenseData.license_project_no + "-P01";
            if (licenseData.license_no === expectedLicenseNo || licenseData.license_no.startsWith(licenseData.license_project_no + "-")) {
              setIsLicenseNoAutoGenerated(true);
            }
          }
        }
      } catch (err) { logger.debug("LicenseStep: load failed", err); }
    })();
  }, [projectId, existingId]);
  
  useEffect(() => {
    if (form.license_project_no && form.license_no) {
      const expectedLicenseNo = form.license_project_no + "-P01";
      if (form.license_no === expectedLicenseNo || form.license_no.startsWith(form.license_project_no + "-")) {
        setIsLicenseNoAutoGenerated(true);
      } else {
        setIsLicenseNoAutoGenerated(false);
      }
    } else if (!form.license_project_no && !form.license_no) {
      setIsLicenseNoAutoGenerated(false);
    }
  }, [form.license_project_no, form.license_no]);

  const LICENSE_TYPES = useMemo(
    () => [
      { value: "new_build_empty_land", label: t("license_type_new_build") },
      { value: "new_build_existing", label: t("license_type_new_build_existing") },
      { value: "extension", label: t("license_type_extension") },
      { value: "renovation", label: t("license_type_renovation") },
      { value: "maintenance", label: t("license_type_maintenance") },
    ],
    [t]
  );

  // Build payload
  const buildPayload = () => {
    const normalized = {
      ...form,
      issue_date: toIsoDate(form.issue_date),
      last_issue_date: toIsoDate(form.last_issue_date),
      expiry_date: toIsoDate(form.expiry_date),
      technical_decision_date: toIsoDate(form.technical_decision_date),
    };

    if (normalized.last_issue_date && normalized.issue_date) {
      const last = new Date(normalized.last_issue_date);
      const first = new Date(normalized.issue_date);
      if (last < first) {
        throw new Error(t("last_issue_date_error"));
      }
    }

    const fd = new FormData();
    Object.entries(normalized).forEach(([k, v]) => {
      if (v === null || v === undefined || v === "") return;
      if (typeof v === "object" && !(v instanceof File) && !(v instanceof Blob)) {
        fd.append(k, JSON.stringify(v));
      } else {
        fd.append(k, v);
      }
    });

    if (form.building_license_file instanceof File) {
      const labelText = t("attach_building_license");
      const renamedFile = renameFileForUpload(form.building_license_file, 'building_license_file', 0, labelText);
      fd.append("building_license_file", renamedFile, renamedFile.name);
    }

    if (consultantStamp instanceof File) {
      const renamedStamp = renameFileForUpload(consultantStamp, 'consultant_stamp', 0, t("consultant_stamp"));
      fd.append("consultant_stamp", renamedStamp, renamedStamp.name);
    }
    if (consultantStampCleared) {
      fd.append("clear_consultant_stamp", "true");
    }

    return fd;
  };

  // Save
  const saveAndNext = async () => {
    setShowLicensePanel(false);

    // Require verification of all AI-extracted fields before saving
    const unverifiedAiFields = aiFilledFields.filter((f) => !verifiedFields[f]);
    if (unverifiedAiFields.length > 0) {
      setErrorMsg(t("verify_ai_fields_required"));
      return;
    }

    // New project flow: validate and pass FormData up (no API call yet)
    if (isNewProject && onLicenseReady) {
      try {
        const payload = buildPayload();
        const snapshot = {
          license_type: form.license_type || "",
          license_project_no: form.license_project_no || "",
          license_no: form.license_no || "",
          issue_date: form.issue_date || "",
          design_consultant_name: form.design_consultant_name || "",
          design_consultant_name_en: form.design_consultant_name_en || "",
          supervision_consultant_name: form.supervision_consultant_name || "",
        };
        onLicenseReady({ formData: payload, snapshot });
      } catch (err) {
        setErrorMsg(err?.message || t("unknown_error"));
      }
      return;
    }

    if (!projectId) {
      setErrorMsg(t("open_specific_project_to_save"));
      return;
    }

    await runSave(async () => {
      const payload = buildPayload();

      let response;
      if (existingId) {
        response = await api.patch(`projects/${projectId}/license/${existingId}/`, payload);
      } else {
        response = await api.post(`projects/${projectId}/license/`, payload);
        if (response?.data?.id) setExistingId(response.data.id);
      }

      try {
        const { data } = await api.get(`projects/${projectId}/license/`);
        if (Array.isArray(data) && data.length > 0) {
          const licenseData = data[0];
          setF("building_license_file", null);
          if (licenseData.building_license_file) setBuildingLicenseFileUrl(licenseData.building_license_file);
          setConsultantStamp(null);
          setConsultantStampCleared(false);
          if (licenseData.consultant_stamp) setExistingConsultantStampUrl(licenseData.consultant_stamp);
          else setExistingConsultantStampUrl(null);
        }
      } catch (e) {
        logger.error("Error reloading license data after save", e);
      }

      if (typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("license-updated", { detail: { projectId } }));
      }

      if (!onNext) {
        updateViewMode(true);
        navTimerRef.current = setTimeout(() => navigate(`/projects/${projectId}`), 500);
        return;
      }
      updateViewMode(true);
      if (typeof onNext === "function") onNext();
    }, (err) => {
      const serverData = err?.response?.data;
      return formatLicenseServerErrors(serverData) || getErrorMessage(err) || t("save_failed");
    });
  };

  return (
    <WizardShell
      footer={!viewMode && (
        <StepActions
          onPrev={onPrev}
          onNext={saveAndNext}
          isLoading={isSaving}
          showPrev={!!onPrev}
          isLastStep={!onNext}
          disableNext={hasBlockingErrors}
        />
      )}
    >
      <ErrorDialog errorMsg={errorMsg} setErrorMsg={setErrorMsg} />

      {/* License side panel */}
      {showLicensePanel && (buildingLicenseFileUrl || form.building_license_file instanceof File) && (
        <div className="siteplan-pdf-panel">
          <div className="siteplan-pdf-panel__header">
            <span className="siteplan-pdf-panel__title">{t("building_license_file")}</span>
            <div className="siteplan-pdf-panel__zoom">
              <button className="siteplan-pdf-panel__zoom-btn" onClick={() => setLicenseZoom(z => Math.max(50, z - 25))}>−</button>
              <span className="siteplan-pdf-panel__zoom-val">{licenseZoom}%</span>
              <button className="siteplan-pdf-panel__zoom-btn" onClick={() => setLicenseZoom(z => Math.min(300, z + 25))}>+</button>
              <button className="siteplan-pdf-panel__zoom-btn" onClick={() => setLicenseZoom(100)} style={{fontSize:"0.8rem",color:"rgba(255,255,255,0.4)"}}>↺</button>
            </div>
            <button className="siteplan-pdf-panel__close" onClick={() => setShowLicensePanel(false)} title={t("close")}>
              <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
              </svg>
            </button>
          </div>
          <div className="siteplan-pdf-panel__body">
            {previewError ? (
              <div className="siteplan-pdf-panel__error">{previewError}</div>
            ) : licensePreviewSrc ? (
              <iframe
                src={licensePreviewSrc}
                title={t("building_license_file")}
                className="siteplan-pdf-panel__iframe"
                style={{ zoom: `${licenseZoom}%` }}
              />
            ) : (
              <div className="siteplan-pdf-panel__loading">{t("loading")}</div>
            )}
          </div>
        </div>
      )}

      {/* Section 1: License details */}
      <div className="wizard-section">
        <div className="wizard-section__header">
          <h4 className="wizard-section__title">{t("license_details")}</h4>
        </div>
        {viewMode ? (
          <FormGrid cols={2}>
            <FormViewField label={t("license_type")} value={LICENSE_TYPES.find(x => x.value === form.license_type)?.label || form.license_type} />
            <FormViewField label={licProjectNoLabel} value={form.license_project_no} />
            <FormViewField label={t("issue_date_first")} value={formatDate(form.issue_date)} />
            <FormViewField label={t("license_no")} value={form.license_no} className="ltr-value" />
            <FormField label={t("attach_building_license")}>
              <FileAttachmentView
                fileUrl={buildingLicenseFileUrl}
                fileName={buildingLicenseFileUrl ? extractFileNameFromUrl(buildingLicenseFileUrl) : ""}
                projectId={projectId}
                endpoint={`projects/${projectId}/license/`}
              />
            </FormField>
          </FormGrid>
        ) : (
          <>
            {/* File upload — full width, always visible */}
            <FormField label={t("attach_building_license")}>
              <FileUpload
                value={form.building_license_file}
                onChange={handleLicenseFileChange}
                accept=".pdf,.jpg,.jpeg,.png"
                maxSizeMB={30}
                showPreview={true}
                existingFileUrl={buildingLicenseFileUrl}
                existingFileName={buildingLicenseFileUrl ? extractFileNameFromUrl(buildingLicenseFileUrl) : ""}
                onRemoveExisting={() => { setBuildingLicenseFileUrl(""); setF("building_license_file", null); }}
                fileType="building_license_file"
                fileIndex={0}
                onPreview={() => setShowLicensePanel(v => !v)}
              />
              {isExtracting && (
                <p style={{ fontSize: "0.75rem", color: "var(--accent)", marginTop: 6, display: "flex", alignItems: "center", gap: 6 }}>
                  <span style={{ display: "inline-block", width: 10, height: 10, borderRadius: "50%", border: "2px solid var(--accent)", borderTopColor: "transparent", animation: "spin 0.7s linear infinite" }} />
                  {t("extracting_data_from_pdf")}
                </p>
              )}
            </FormField>

            {/* Fields appear after file uploaded */}
            {(buildingLicenseFileUrl || form.building_license_file) && (
              <div className="form-grid cols-2 mt-8">
                <VerifiableField fieldName="license_type" verified={verifiedFields.license_type} onToggle={toggleVerify} viewMode={viewMode}>
                  <FormField label={t("license_type")}>
                    <RtlSelect
                      className="rtl-select"
                      options={LICENSE_TYPES}
                      value={form.license_type}
                      onChange={(v) => setF("license_type", v)}
                      placeholder={t("select_license_type")}
                    />
                  </FormField>
                </VerifiableField>
                <VerifiableField fieldName="license_project_no" verified={verifiedFields.license_project_no} onToggle={toggleVerify} viewMode={viewMode}>
                  <FormField label={licProjectNoLabel}>
                    <FormInput
                      value={form.license_project_no}
                      onChange={(e) => {
                        const cleaned = e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, "");
                        const formatted = formatProjectNumber(cleaned);
                        setF("license_project_no", formatted);
                        if (formatted) {
                          if (!form.license_no || isLicenseNoAutoGenerated) {
                            setF("license_no", formatted + "-P01");
                            setIsLicenseNoAutoGenerated(true);
                          }
                        } else {
                          if (isLicenseNoAutoGenerated) {
                            setF("license_no", "");
                            setIsLicenseNoAutoGenerated(false);
                          }
                        }
                      }}
                      className="input--uppercase"
                    />
                  </FormField>
                </VerifiableField>
                <VerifiableField fieldName="issue_date" verified={verifiedFields.issue_date} onToggle={toggleVerify} viewMode={viewMode}>
                  <FormField label={t("issue_date_first")}>
                    <DateInput value={form.issue_date || ""} onChange={(value) => setF("issue_date", value)} />
                  </FormField>
                </VerifiableField>
                <VerifiableField fieldName="license_no" verified={verifiedFields.license_no} onToggle={toggleVerify} viewMode={viewMode}>
                  <FormField label={t("license_no")}>
                    <FormInput
                      value={form.license_no}
                      onChange={(e) => {
                        const newValue = e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, "");
                        setF("license_no", newValue);
                        if (newValue !== form.license_project_no + "-P01") setIsLicenseNoAutoGenerated(false);
                      }}
                      className="input--uppercase input--ltr"
                      dir="ltr"
                    />
                  </FormField>
                </VerifiableField>
              </div>
            )}
          </>
        )}
      </div>

      {/* Section 2: Owner details - shown only in view mode */}
      {viewMode && (
        <div className="wizard-section">
          <div className="wizard-section__header">
            <h4 className="wizard-section__title">{t("owner_details")}</h4>
          </div>
          {owners && owners.length ? (
            owners.map((o, i) => (
              <div key={o.id || o.id_number || i} className="owner-block">
                <FormGrid cols={3}>
                  <FormViewField label={t("owner_name_ar")} value={o.owner_name_ar} />
                  <FormViewField label={t("owner_name_en")} value={o.owner_name_en} />
                  <div />
                </FormGrid>
              </div>
            ))
          ) : (
            <div className="wizard-empty-state">
              {t("no_owners_in_siteplan")}
            </div>
          )}
        </div>
      )}

      {/* Section 3: Consultant */}
      <div className="wizard-section">
        <div className="wizard-section__header">
          <h4 className="wizard-section__title">{t("consultant_details")}</h4>
        </div>
        <FormField label={t("consultant_same_question")}>
          <YesNoChips
            value={form.consultant_same ? "yes" : "no"}
            onChange={(v) => {
              const same = v === "yes";
              setF("consultant_same", same);
              if (same) {
                setF("supervision_consultant_name", form.design_consultant_name);
                setF("supervision_consultant_name_en", form.design_consultant_name_en);
                setF("supervision_consultant_license_no", form.design_consultant_license_no);
              } else {
                setF("supervision_consultant_name", "");
                setF("supervision_consultant_name_en", "");
                setF("supervision_consultant_license_no", "");
              }
            }}
          />
        </FormField>

        {/* If single consultant -> one card */}
        {form.consultant_same ? (
          <div className="wizard-section-card wizard-mt-4">
            <div className="wizard-section-card__header">
              <h5 className="wizard-section-card__title">
              {t("consultant")}
            </h5>
            </div>
            <PersonField
              type="consultant"
              label={t("consultant")}
              licenseLabel={t("consultant_municipality_license")}
              nameValue={form.design_consultant_name}
              nameEnValue={form.design_consultant_name_en}
              licenseValue={form.design_consultant_license_no}
              onNameChange={(v) => {
                setF("design_consultant_name", v);
                setF("supervision_consultant_name", v);
              }}
              onNameEnChange={(v) => {
                setF("design_consultant_name_en", v);
                setF("supervision_consultant_name_en", v);
              }}
              onLicenseChange={(v) => {
                const formatted = formatCNLicense(v);
                setF("design_consultant_license_no", formatted);
                setF("supervision_consultant_license_no", formatted);
              }}
              isView={viewMode}
              onSelect={(c) => {
                setF("supervision_consultant_name", c.name || "");
                setF("supervision_consultant_name_en", c.name_en || "");
                setF("supervision_consultant_license_no", c.license || "");
              }}
              verifiedFields={verifiedFields}
              onToggleVerify={toggleVerify}
              fieldPrefix="design_"
            />
          </div>
        ) : (
          /* If two consultants -> two cards */
          <FormGrid cols={2} gap="md" className="wizard-mt-4">
            {/* Design consultant card */}
            <div className="wizard-section-card">
              <div className="wizard-section-card__header">
                <h5 className="wizard-section-card__title">
                {t("design_consultant")}
              </h5>
              </div>
              <PersonField
                type="consultant"
                label={t("consultant")}
                licenseLabel={t("consultant_municipality_license")}
                nameValue={form.design_consultant_name}
                nameEnValue={form.design_consultant_name_en}
                licenseValue={form.design_consultant_license_no}
                onNameChange={(v) => setF("design_consultant_name", v)}
                onNameEnChange={(v) => setF("design_consultant_name_en", v)}
                onLicenseChange={(v) => {
                  const formatted = formatCNLicense(v);
                  setF("design_consultant_license_no", formatted);
                }}
                isView={viewMode}
                verifiedFields={verifiedFields}
                onToggleVerify={toggleVerify}
                fieldPrefix="design_"
              />
            </div>

            {/* Supervision consultant card */}
            <div className="wizard-section-card">
              <div className="wizard-section-card__header">
                <h5 className="wizard-section-card__title">
                {t("supervision_consultant")}
              </h5>
              </div>
              <PersonField
                type="consultant"
                label={t("consultant")}
                licenseLabel={t("consultant_municipality_license")}
                nameValue={form.supervision_consultant_name}
                nameEnValue={form.supervision_consultant_name_en}
                licenseValue={form.supervision_consultant_license_no}
                onNameChange={(v) => setF("supervision_consultant_name", v)}
                onNameEnChange={(v) => setF("supervision_consultant_name_en", v)}
                onLicenseChange={(v) => {
                  const formatted = formatCNLicense(v);
                  setF("supervision_consultant_license_no", formatted);
                }}
                isView={viewMode}
                verifiedFields={verifiedFields}
                onToggleVerify={toggleVerify}
                fieldPrefix="supervision_"
              />
            </div>
          </FormGrid>
        )}
      </div>

      {/* Section 4: Consultant Stamp */}
      <div className="wizard-section">
        <div className="wizard-section__header">
          <h4 className="wizard-section__title">{t("consultant_stamp")}</h4>
        </div>
        <div className="wizard-section-card" style={{ maxWidth: 480 }}>
          {viewMode ? (
            existingConsultantStampUrl ? (
              <img
                src={existingConsultantStampUrl}
                alt={t("consultant_stamp")}
                style={{ maxHeight: 120, maxWidth: 240, objectFit: "contain", display: "block" }}
              />
            ) : (
              <span className="wizard-empty-value">—</span>
            )
          ) : (
            <FileUpload
              value={consultantStamp}
              onChange={(f) => {
                setConsultantStamp(f);
                if (!f) setConsultantStampCleared(true);
              }}
              accept=".jpg,.jpeg,.png,.webp"
              maxSizeMB={5}
              existingFileUrl={existingConsultantStampUrl}
              existingFileName={existingConsultantStampUrl ? "Consultant_Stamp" : ""}
              onRemoveExisting={() => {
                setExistingConsultantStampUrl(null);
                setConsultantStampCleared(true);
              }}
              fileType="consultant_stamp"
              fileIndex={0}
            />
          )}
        </div>
      </div>

    </WizardShell>
  );
}
