import { useMemo, useEffect, useState, useRef, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { useLanguage } from "../../../../hooks";
import { useParams } from 'react-router-dom';
import { FiCamera, FiX } from "react-icons/fi";

import {
  FormField,
  FormInput,
  FormChips,
  FormViewField
} from "../../../../components/ui/form";

import WizardShell from "../components/WizardShell";
import StepActions from "../components/StepActions";
import ErrorDialog from "../components/ErrorDialog";
import Button from "../../../../components/common/Button";

import { api, API_BASE_URL } from "../../../../services/api";
import { buildFileUrl } from "../../../../utils/helpers/file";
import { PROJECT_TYPES, CONTRACT_TYPES, PROJECT_CATEGORIES, MAINTENANCE_TYPES, CONTRACT_TYPE_TO_CATEGORY } from "../../../../utils/constants";
import { formatInternalCode, isAutoGeneratedCode } from "../../../../utils/formatters/id";
import { formatServerErrors } from "../../../../utils/helpers";
import { logger } from "../../../../utils/logger";
import useViewMode from "../hooks/useViewMode";
import useTenantNavigate from '../../../../hooks/useTenantNavigate';

const CONTRACT_CLASSIFICATION = [
  {
    value: "housing_loan_program",
    labelKey: "contract.classification.housing_loan_program.label",
    descKey: "contract.classification.housing_loan_program.desc",
  },
  {
    value: "private_funding",
    labelKey: "contract.classification.private_funding.label",
    descKey: "contract.classification.private_funding.desc",
  },
  {
    value: "ruler_court_funding",
    labelKey: "contract.classification.ruler_court_funding.label",
    descKey: "contract.classification.ruler_court_funding.desc",
  },
];

export default function ProjectSetupStep({
  value,
  onChange,
  onNext,
  onPrev,
  isView,
  onSaved,
  isNewProject = false,
  isSuperAdmin = false,
}) {
  const { t } = useTranslation();
  const navigate = useTenantNavigate();
  const { isArabic: isAR } = useLanguage();
  const { projectId } = useParams();

  const { projectType, contractType, internalCode, legacyCode, contractClassification, projectCategory, maintenanceType, contractYear } = value || {};
  const set = (k, v) => onChange({ ...value, [k]: v });

  // Project image state
  const [projectImage, setProjectImage] = useState(null); // File object for new upload
  const [projectImagePreview, setProjectImagePreview] = useState(null); // Preview URL (existing or new)
  const imageInputRef = useRef(null);
  const navTimerRef = useRef(null);

  useEffect(() => {
    return () => clearTimeout(navTimerRef.current);
  }, []);

  const handleImageSelect = useCallback((e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    // Validate: images only, max 5MB
    if (!file.type.startsWith("image/")) return;
    if (file.size > 5 * 1024 * 1024) return;
    setProjectImage(file);
    setProjectImagePreview(URL.createObjectURL(file));
    // Store image in parent state so WizardPage can access it for new projects
    onChange({ ...value, _projectImageFile: file });
  }, [value, onChange]);

  const handleImageRemove = useCallback(() => {
    setProjectImage(null);
    setProjectImagePreview(null);
    if (imageInputRef.current) imageInputRef.current.value = "";
    // Clear image from parent state
    onChange({ ...value, _projectImageFile: null });
  }, [value, onChange]);
  
  // Dep array is intentionally limited to [projectId, isView] so this only runs
  // on mount or when the project/view changes -- not on every `value`/`onChange`
  // update, which would cause an infinite re-fetch loop.
  useEffect(() => {
    if (!projectId || isView) return;

    let mounted = true;

    (async () => {
      try {
        const { data } = await api.get(`projects/${projectId}/contract/`);
        if (!mounted) return;

        if (Array.isArray(data) && data.length > 0 && data[0].contract_classification) {
          const classification = data[0].contract_classification;
          onChange((prev) => {
            if ((prev?.contractClassification || "") === classification) return prev;
            return { ...prev, contractClassification: classification };
          });
        }
      } catch (e) {
        // ignore — contractClassification is optional
      }
    })();

    return () => {
      mounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, isView]);

  const categoryReady = !!projectCategory && (projectCategory !== "MNT" || !!maintenanceType);
  const baseSelected = !!contractType && !!projectCategory;

  const allowSitePlanFlow = !!contractType;

  const canProceed = baseSelected && allowSitePlanFlow && categoryReady;

  const [errorMsg, setErrorMsg] = useState("");

  const [viewMode, updateViewMode] = useViewMode(isView, false, () => {});
  const isReadOnly = viewMode;

  useEffect(() => {
    if (!projectId) return;
    
    let mounted = true;
    
    (async () => {
      try {
        const { data } = await api.get(`projects/${projectId}/`);
        if (!mounted) return;
        
        // Load project image if exists
        if (data?.project_image && !projectImagePreview) {
          const imgUrl = data.project_image.startsWith("http")
            ? data.project_image
            : buildFileUrl(data.project_image);
          setProjectImagePreview(imgUrl);
        }

        const fromApi = {
          projectType: data?.project_type || "",
          contractType: data?.contract_type || "",
          internalCode: data?.internal_code || "",
          legacyCode: data?.legacy_code || "",
          projectCategory: data?.project_category || "",
          maintenanceType: data?.maintenance_type || "",
          contractYear: data?.contract_year || new Date().getFullYear(),
        };

        if (
          fromApi.projectType !== (value?.projectType || "") ||
          fromApi.contractType !== (value?.contractType || "") ||
          fromApi.internalCode !== (value?.internalCode || "") ||
          fromApi.legacyCode !== (value?.legacyCode || "") ||
          fromApi.projectCategory !== (value?.projectCategory || "") ||
          fromApi.maintenanceType !== (value?.maintenanceType || "")
        ) {
          // Use functional update to preserve contractClassification set by the parallel contract API call
          onChange((prev) => ({ ...prev, ...fromApi }));
        }
      } catch (e) {
        logger.error("Error loading project data", e);
      }
    })();
    
    return () => {
      mounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);
  
  // Auto-set project category when contract type changes
  const handleContractTypeChange = useCallback((v) => {
    const autoCategory = CONTRACT_TYPE_TO_CATEGORY[v] || "";
    onChange({
      ...value,
      contractType: v,
      projectCategory: autoCategory,
      // Reset maintenance type if not MNT
      maintenanceType: autoCategory === "MNT" ? (value?.maintenanceType || "") : "",
    });
  }, [value, onChange]);

  const handleCategoryChange = useCallback((v) => {
    onChange({
      ...value,
      projectCategory: v,
      maintenanceType: v === "MNT" ? (value?.maintenanceType || "") : "",
    });
  }, [value, onChange]);

  const contractClassificationOptions = useMemo(
    () =>
      CONTRACT_CLASSIFICATION.map((item) => ({
        value: item.value,
        label: t(item.labelKey),
        desc: t(item.descKey),
      })),
    [t]
  );

  const chipsProjectTypes = useMemo(() => PROJECT_TYPES[isAR ? "ar" : "en"], [isAR]);
  const contractTypes = useMemo(() => CONTRACT_TYPES[isAR ? "ar" : "en"], [isAR]);
  const projectCategories = useMemo(() => PROJECT_CATEGORIES[isAR ? "ar" : "en"], [isAR]);
  const maintenanceTypes = useMemo(() => MAINTENANCE_TYPES[isAR ? "ar" : "en"], [isAR]);

  const labelMap = useMemo(() => {
    const m = (pairs) =>
      pairs.reduce((acc, [v, label]) => {
        acc[v] = label;
        return acc;
      }, {});
    return {
      projectType: m(chipsProjectTypes),
      contractType: m(contractTypes),
      projectCategory: m(projectCategories),
      maintenanceType: m(maintenanceTypes),
    };
  }, [chipsProjectTypes, contractTypes, projectCategories, maintenanceTypes]);

  const handleSaveAndNext = async () => {
    // Validate: project_category is required
    if (!projectCategory) {
      setErrorMsg(t("project_category_required"));
      return;
    }

    // Validate: MNT requires maintenance_type
    if (projectCategory === "MNT" && !maintenanceType) {
      setErrorMsg(t("maintenance_type_required"));
      return;
    }

    if (isNewProject) {
      onChange({
        ...value,
        contractClassification: contractClassification || "",
        projectCategory: projectCategory || "",
        maintenanceType: maintenanceType || "",
        contractYear: contractYear || new Date().getFullYear(),
      });

      if (onNext && canProceed) {
        onNext();
      }
      return;
    }

    if (!projectId) {
      setErrorMsg(t("open_specific_project_to_save"));
      return;
    }

    try {
      setErrorMsg("");

      // Save project fields (JSON) - internal_code is auto-generated, legacy_code is optional
      const payload = {
        contract_type: contractType || "",
        project_category: projectCategory || "",
        maintenance_type: maintenanceType || "",
        contract_year: contractYear || new Date().getFullYear(),
        legacy_code: legacyCode || "",
      };
      await api.patch(`projects/${projectId}/`, payload);

      // Upload image separately using native fetch with cookie auth
      if (projectImage && projectImage.size > 0) {
        const { getCsrfToken } = await import("../../../../utils/cookies");
        const imgForm = new FormData();
        imgForm.append("project_image", projectImage, projectImage.name);
        const headers = {};
        const csrf = getCsrfToken();
        if (csrf) headers["X-CSRFToken"] = csrf;
        const res = await fetch(`${API_BASE_URL}projects/${projectId}/`, {
          method: "PATCH",
          credentials: "include",
          headers,
          body: imgForm,
        });
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.project_image?.[0] || errData?.detail || "Image upload failed");
        }
      }
      
      if (contractClassification) {
        try {
          const contractRes = await api.get(`projects/${projectId}/contract/`);
          if (Array.isArray(contractRes.data) && contractRes.data.length > 0) {
            const contractId = contractRes.data[0].id;
            await api.patch(`projects/${projectId}/contract/${contractId}/`, {
              contract_classification: contractClassification,
            });
          } else {
            await api.post(`projects/${projectId}/contract/`, {
              contract_classification: contractClassification,
            });
          }
          onChange({ ...value, contractClassification });
        } catch (e) {
          logger.error("Error saving contract classification", e);
        }
      }

      if (typeof onSaved === "function") {
        onSaved();
      }

      // When editing (not a new project), return to view directly without moving to another step
      if (!isNewProject) {
        updateViewMode(true);
        window.dispatchEvent(new CustomEvent("project-updated", { detail: { projectId } }));
        navTimerRef.current = setTimeout(() => {
          navigate(`/projects/${projectId}`);
        }, 500);
      } else if (onNext && canProceed) {
        onNext();
      } else {
        updateViewMode(true);
      }
    } catch (e) {
      const formatted = formatServerErrors(e?.response?.data);
      const msg = formatted || e?.message || t("save_project_error");
      setErrorMsg(msg);
    }
  };

  // Compute which step is currently active (first incomplete)
  const activeStepKey = useMemo(() => {
    if (!contractType && !isReadOnly) return "contract";
    if (!categoryReady && !isReadOnly) return "category";
    if (!contractClassification && !viewMode && !isReadOnly) return "classification";
    return "image";
  }, [categoryReady, isReadOnly, contractType, contractClassification, viewMode]);

  const cardClass = (key, isCompleted) => {
    const cls = ["wizard-section-card", "wizard-reveal"];
    if (isCompleted) cls.push("wizard-section-card--completed");
    if (key === activeStepKey) cls.push("wizard-section-card--active");
    return cls.join(" ");
  };

  // Build visible step cards
  const visibleCards = [];
  let stepN = 0;

  // 1: Project Image — always visible (first card)
  visibleCards.push(
    <div key="image" className="wizard-section-card wizard-reveal wizard-image-card">
      <div className="wizard-section__header">
        <h4 className="wizard-section__title">{t("project_image")}</h4>
        <p className="wizard-section__subtitle">— {t("optional")}</p>
      </div>
      <div className="wizard-section__body">
        {isReadOnly ? (
          projectImagePreview ? (
            <div className="project-image-preview">
              <img src={projectImagePreview} alt={t("project_image")} />
            </div>
          ) : (
            <FormViewField value={null} />
          )
        ) : (
          <div className="project-image-upload">
            {projectImagePreview ? (
              <div className="project-image-preview project-image-preview--editable">
                <img src={projectImagePreview} alt={t("project_image")} />
                <div className="project-image-preview__overlay">
                  <Button type="button" variant="ghost" size="sm" className="project-image-preview__btn"
                    onClick={() => imageInputRef.current?.click()} title={t("change")}>
                    <FiCamera />
                  </Button>
                  <Button type="button" variant="danger" size="sm"
                    className="project-image-preview__btn project-image-preview__btn--remove"
                    onClick={handleImageRemove} title={t("remove")}>
                    <FiX />
                  </Button>
                </div>
              </div>
            ) : (
              <Button type="button" variant="outline" className="project-image-upload__placeholder"
                onClick={() => imageInputRef.current?.click()}>
                <FiCamera className="project-image-upload__icon" />
                <span>{t("upload_project_image")}</span>
              </Button>
            )}
            <input ref={imageInputRef} type="file" accept="image/*" onChange={handleImageSelect} hidden />
          </div>
        )}
      </div>
    </div>
  );

  // 2: Auto-generated Project Code — show for existing projects (real code) or new projects (preview)
  const codePreview = useMemo(() => {
    if (internalCode) return internalCode;
    const year = contractYear || new Date().getFullYear();
    const YEAR_INDEX_BASE = 2026, YEAR_INDEX_OFFSET = 37;
    const yi = YEAR_INDEX_OFFSET + (year - YEAR_INDEX_BASE);
    const cat = projectCategory || CONTRACT_TYPE_TO_CATEGORY[contractType] || "CON";
    if (cat === "MNT" && maintenanceType) return `${yi}-MNT-${maintenanceType}-####-${year}`;
    return `${yi}-${cat}-####-${year}`;
  }, [internalCode, contractType, projectCategory, maintenanceType, contractYear]);

  if (internalCode || isNewProject) {
    visibleCards.push(
      <div key="code" className={`wizard-section-card wizard-reveal${internalCode ? " wizard-section-card--completed" : ""}`}>
        <div className="wizard-section__header">
          {internalCode && <div className="wizard-section__step-badge">{"✓"}</div>}
          <h4 className="wizard-section__title">{t("internal_project_code")}</h4>
          {!internalCode && <p className="wizard-section__subtitle" style={{ color: "var(--accent)", fontSize: "0.75rem" }}>— {t("code_will_be_set_on_save")}</p>}
        </div>
        <div className="wizard-section__body">
          <FormViewField
            value={codePreview}
            className="mono"
            style={!internalCode ? { opacity: 0.55, fontStyle: "italic", letterSpacing: "0.05em" } : {}}
          />
        </div>
      </div>
    );
  }

  // 2b: Legacy/Old Project Code — optional, shown only if project already has one OR user is editing
  if (!isNewProject) {
    visibleCards.push(
      <div key="legacy-code" className={`wizard-section-card wizard-reveal${legacyCode ? " wizard-section-card--completed" : ""}`}>
        <div className="wizard-section__header">
          {legacyCode && <div className="wizard-section__step-badge">{"✓"}</div>}
          <h4 className="wizard-section__title">{t("legacy_project_code")}</h4>
          <p className="wizard-section__subtitle">— {t("optional")}</p>
        </div>
        <div className="wizard-section__body">
          {isReadOnly ? (
            <FormViewField value={legacyCode || null} />
          ) : (
            <input
              className="input"
              value={legacyCode || ""}
              onChange={(e) => set("legacyCode", e.target.value)}
              placeholder={t("legacy_project_code_placeholder")}
            />
          )}
        </div>
      </div>
    );
  }

  // 3: Contract Type — always visible
  stepN++;
  visibleCards.push(
    <div key="contract" className={cardClass("contract", !!contractType)} data-step={stepN}>
      <div className="wizard-section__header">
        <div className="wizard-section__step-badge">{contractType ? "✓" : stepN}</div>
        <h4 className="wizard-section__title">{t("setup_contract_type_title")}</h4>
      </div>
      <div className="wizard-section__body">
        {isReadOnly ? (
          <FormViewField value={labelMap.contractType[contractType] || null} />
        ) : (
          <FormChips options={contractTypes} value={contractType} onChange={handleContractTypeChange} />
        )}
      </div>
    </div>
  );


  // 4: Project Category (CON/MNT/REN/FIT) — visible after contract type selected
  if (isReadOnly || !!contractType) {
    stepN++;
    visibleCards.push(
      <div key="category" className={cardClass("category", !!projectCategory)} data-step={stepN}>
        <div className="wizard-section__header">
          <div className="wizard-section__step-badge">{projectCategory ? "✓" : stepN}</div>
          <h4 className="wizard-section__title">{t("project_category_title")}</h4>
        </div>
        <div className="wizard-section__body">
          {isReadOnly ? (
            <FormViewField value={labelMap.projectCategory[projectCategory] || null} />
          ) : (
            <FormChips options={projectCategories} value={projectCategory} onChange={handleCategoryChange} />
          )}
        </div>
      </div>
    );
  }

  // 5: Maintenance Type (AM/SM) — only for MNT
  if (projectCategory === "MNT") {
    stepN++;
    visibleCards.push(
      <div key="maint" className={cardClass("maint", !!maintenanceType)} data-step={stepN}>
        <div className="wizard-section__header">
          <div className="wizard-section__step-badge">{maintenanceType ? "✓" : stepN}</div>
          <h4 className="wizard-section__title">{t("maintenance_type_title")}</h4>
        </div>
        <div className="wizard-section__body">
          {isReadOnly ? (
            <FormViewField value={labelMap.maintenanceType[maintenanceType] || null} />
          ) : (
            <FormChips options={maintenanceTypes} value={maintenanceType} onChange={(v) => set("maintenanceType", v)} />
          )}
        </div>
      </div>
    );
  }

  // 4/5: Funding Classification
  if (viewMode || contractClassification || !!contractType) {
    stepN++;
    visibleCards.push(
      <div key="classification" className={cardClass("classification", !!contractClassification)} data-step={stepN}>
        <div className="wizard-section__header">
          <div className="wizard-section__step-badge">{contractClassification ? "✓" : stepN}</div>
          <h4 className="wizard-section__title">{t("contract.sections.classification")}</h4>
        </div>
        <div className="wizard-section__body">
          {isReadOnly ? (
            <FormViewField
              value={contractClassificationOptions.find((m) => m.value === contractClassification)?.label || null}
            />
          ) : (
            <FormChips
              options={contractClassificationOptions.map((m) => [m.value, m.label, m.desc])}
              value={contractClassification}
              onChange={(v) => set("contractClassification", v)}
              disabled={!contractType}
            />
          )}
        </div>
      </div>
    );
  }

  // Chunk cards into rows of 2
  const rows = [];
  for (let i = 0; i < visibleCards.length; i += 2) {
    rows.push(visibleCards.slice(i, i + 2));
  }

  return (
    <WizardShell
      footer={!isReadOnly && (
        <StepActions
          onPrev={onPrev}
          onNext={handleSaveAndNext}
          disableNext={!contractType || !categoryReady}
          showPrev={!!onPrev && !isNewProject}
          isLastStep={!isNewProject || !onNext}
        />
      )}
    >
      <ErrorDialog errorMsg={errorMsg} setErrorMsg={setErrorMsg} title="error" />

      <div className="wizard-form-grid wizard-form-grid--sequential">
        {rows.map((rowCards, rowIdx) => (
          <div key={rowIdx} className="wizard-step-row">
            {rowCards}
          </div>
        ))}
      </div>
    </WizardShell>
  );
}
